### PR TITLE
fix failfast

### PR DESCRIPTION
**Pull request by FFroehlich**

### CODE REVIEW

**Comment by FFroehlich** [comment]
will add a test for this tomorrow ...

**Comment by FFroehlich** [comment]
> Empty slots will cause trouble in Python, or why do we need that?

Correct.

**Comment by dweindl** [comment]
Can you add a comment on that? Otherwise I might optimize it out soon ;)

**Comment by FFroehlich** [comment]
> Can you add a comment on that? Otherwise I might optimize it out soon ;)

done, also added a testcase that will hopefull prevent you from ignoring the comment :D

**Pull request merged**
