### PR TITLE
Run SBML test suite using github actions instead of travisCI

### LINKED ISSUE #571: SBML Testsuite is taking too long
Split testcases in 2-3 batches and execute in parallel jobs? Would be nice if we can skip them in regular builds and skip os x builds in the cron setting.

### LINKED ISSUE #731: Running SBML test suite as travis-ci cron job failing since months?
See https://travis-ci.com/ICB-DCM/AMICI/builds

To be checked if problem persists with updated `master`.

### LINKED ISSUE #775: Allow running individual tests from SBML test suite via CLI
Should allow for something like:
`testSBMLSuite.py 1,3-5,8`

### PR DESCRIPTION
**Pull request by dweindl**
* Run SBML test suite using github actions instead of travisCI (Closes #571)
* Allow running individual tests from SBML test suite via CLI (Closes #775)
* Fix SBML test suite issues (Closes #731)
* [x] On merge to master
* [x] Remove travis cron job?
* [x] #771 
* [x] #773 
* [x] #774 

Current run time for test suite is about 1h10

### CODE REVIEW

**Comment by dweindl** [comment]
Looks quite usable. Currently test output is delayed by like 10min, not sure why.

**Comment by dweindl** [comment]
Seems like the time limits are currently not enforced. One job running for >10h already.

**Comment by dweindl** [comment]
Travis failing because http://www.valgrind.org/ seems to down so that downloading valgrind fails.

**Comment by FFroehlich** [comment]
Ideally I would like to have this as required check for merging into master.

**Comment by dweindl** [comment]
> Ideally I would like to have this as required check for merging into master.

For that to make sense, we should keep track of the tests we were able to pass. Only fail the github check upon regression, but not when known-to-fail tests fail.

**Comment by FFroehlich** [comment]
There should not be any known-to-fail tests (which was true a couple of months ago and only changed with recent modifications).
The only known to fail case involves NaNs in the jacobian and is hardcoded in the testsuite script.

**Comment by FFroehlich** [comment]
Is it possible to also submit results to the testsuite website on release?

**Comment by dweindl** [comment]
> There should not be any known-to-fail tests [...]

Okay, that was imprecise. I meant known-to-not-pass. But true, skipped test will be ignored. The reason for failure were only the two issues i wrote in the top most. One of them being fixed now, the other one waiting for @paulstapor .

> Is it possible to also submit results to the testsuite website on release?

To where exactly? Can be done, sure. Maybe open a respective issue.

**Comment by dweindl** [comment]
@paulstapor #774 should also be fixed here (you were assigned)

**Comment by FFroehlich** [comment]
fixed #774, but looks like someone broke `_parse_logical_operators()`

**Pull request merged**
