### PR TITLE
Feature special inputs

### LINKED ISSUE #615: Add support for piecewise in Python SBML import
Sympy has a [piecewise function](https://docs.sympy.org/latest/modules/functions/elementary.html#sympy-functions-elementary-piecewise) available, but mind the difference in arguments to the [SBML piecewise](http://sbml.org/Software/libSBML/5.17.0/docs//python-api/namespacelibsbml.html#a3f253fbb0880b35181342b5a9e9feb31)

### PR DESCRIPTION
**Pull request by paulstapor**
This should fix the problem with piecewise functions (fixes #615 ).

### CODE REVIEW

**Comment by FFroehlich** [comment]
Did you check that testSBMLSuite passes?

**Comment by dweindl** [comment]
> Did you check that testSBMLSuite passes?

I got: 
```
TestCase 00190 was skipped: Encountered unsupported expression "piecewise" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a KineticLaw: "piecewise(p1, False, p2)"!
TestCase 00191 was skipped: Encountered unsupported expression "piecewise" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a KineticLaw: "piecewise(p1, S2 >= 4, p2)"!
TestCase 00192 was skipped: Encountered unsupported expression "piecewise" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a KineticLaw: "piecewise(p1, S2 > 7, p2)"!
TestCase 00193 was skipped: Encountered unsupported expression "piecewise" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a KineticLaw: "piecewise(p1, S1 <= 4, p2)"!
TestCase 00194 was skipped: Encountered unsupported expression "piecewise" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a KineticLaw: "piecewise(p1, S1 < 2.5, p2)"!
TestCase 00195 was skipped: Encountered unsupported expression "piecewise" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a KineticLaw: "piecewise(p1, True, p2)"!
```

@paulstapor : Can you check that?

**Comment by paulstapor** [comment]
> @paulstapor : Can you check that?

😞 This looks rather bad... It worked fine for the models in the benchmark collection, however...
I will check it, yes.

**Comment by paulstapor** [comment]
Okay, looks good now. SBMLSuite gives only these errors now:
```
TestCase 00198 was skipped: Kinetic law "piecewise(p1, (S2 > 4) && (S1 < 5) && (S2 < 8), p2)" contains an unsupported expression!
TestCase 00200 was skipped: Kinetic law "piecewise(p1, (S2 < 2) || (S2 > 4) || (S2 < 1), p2)" contains an unsupported expression!
TestCase 00276 was skipped: Kinetic law "piecewise(p1, (S2 > 4) && (S1 < 5) && (S2 < 8), p2)" contains an unsupported expression!
TestCase 00278 was skipped: Kinetic law "piecewise(p1, (S2 < 2) || (S2 > 4) || (S2 < 1), p2)" contains an unsupported expression!
```
And they are due to "and", "or" handling, as all the other models with "piecewise" seem to work now. Especially the test cases you mentioned passed.
I can take care of further things soon, for the moment I would be happy to merge this, since this should push the number of models from the Benchmark collection a bit higher.

**Pull request merged**
