### PR TITLE
Cleanup and reorganize tests

### PR DESCRIPTION
**Pull request by dweindl**
* Better organization of tests
* Make test cases independent
* Avoid model re-import -> speed up CI

### CODE REVIEW

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/tests/test_swig_interface.py  9
- python/tests/test_petab_import.py  6
- python/tests/test_pandas.py  10
- python/tests/test_sbml_import.py  9
- python/tests/test_ode_export.py  11
- python/tests/test_misc.py  4
- python/tests/conftest.py  2
- python/tests/test_parameter_mapping.py  6
- python/tests/test_pysb.py  12
- python/tests/test_hdf5.py  7
         

Clones added
============
- python/tests/test_sbml_import.py  5
- python/tests/test_misc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5276301&bid=17278822)

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/tests/test_petab_import.py  6
- python/tests/test_pandas.py  10
- python/tests/test_sbml_import.py  9
- python/tests/test_pysb.py  12
- python/tests/test_hdf5.py  7
- python/tests/conftest.py  4
- python/tests/test_misc.py  4
- python/tests/test_preequilibration.py  7
- python/tests/test_ode_export.py  11
- python/tests/test_parameter_mapping.py  6
- python/tests/test_swig_interface.py  9
         

Clones added
============
- python/tests/test_sbml_import.py  5
- python/tests/test_misc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5276301&bid=17278822)

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/tests/test_ode_export.py  11
- python/tests/test_sbml_import.py  9
- python/tests/test_hdf5.py  7
- python/tests/test_pandas.py  10
- python/tests/test_petab_import.py  6
- python/tests/test_swig_interface.py  9
- python/tests/test_parameter_mapping.py  6
- python/tests/test_pysb.py  12
- python/tests/conftest.py  4
- python/tests/test_preequilibration.py  7
- python/tests/test_misc.py  4
         

Clones added
============
- python/tests/test_sbml_import.py  5
- python/tests/test_misc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5276301&bid=17278822)

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/tests/test_hdf5.py  7
- python/tests/test_sbml_import.py  9
- python/tests/test_pandas.py  10
- python/tests/test_pysb.py  12
- python/tests/test_petab_import.py  6
- python/tests/test_parameter_mapping.py  6
- python/tests/test_ode_export.py  11
- python/tests/test_misc.py  4
- python/tests/test_preequilibration.py  7
- python/tests/test_swig_interface.py  9
- python/tests/conftest.py  4
         

Clones added
============
- python/tests/test_sbml_import.py  5
- python/tests/test_misc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5276301&bid=17278822)

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- python/tests/test_pysb.py  12
- python/tests/test_hdf5.py  7
- python/tests/test_sbml_import.py  9
- python/tests/test_swig_interface.py  9
- python/tests/test_petab_import.py  6
- python/tests/test_misc.py  4
- python/tests/test_ode_export.py  11
- python/tests/test_pandas.py  10
- python/tests/test_preequilibration.py  7
- python/tests/test_parameter_mapping.py  6
- python/tests/conftest.py  4
         

Clones added
============
- python/tests/test_sbml_import.py  5
- python/tests/test_misc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5276301&bid=17278822)

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- python/tests/test_swig_interface.py  9
- python/tests/test_pysb.py  12
- python/tests/test_petab_import.py  6
- python/tests/test_pandas.py  10
- python/tests/conftest.py  4
- python/tests/test_misc.py  4
- python/tests/test_ode_export.py  11
- python/tests/test_parameter_mapping.py  6
- python/tests/test_preequilibration.py  7
- python/tests/test_hdf5.py  7
- python/tests/test_sbml_import.py  9
         

Clones added
============
- python/tests/test_misc.py  1
- python/tests/test_sbml_import.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5276301&bid=17278822)

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- python/tests/test_misc.py  4
- python/tests/test_preequilibration.py  7
- python/tests/test_hdf5.py  7
- python/tests/test_swig_interface.py  9
- python/tests/test_ode_export.py  11
- python/tests/conftest.py  4
- python/tests/test_parameter_mapping.py  6
- python/tests/test_pysb.py  12
- python/tests/test_sbml_import.py  9
- python/tests/test_pandas.py  10
- python/tests/test_petab_import.py  6
         

Clones added
============
- python/tests/test_misc.py  1
- python/tests/test_sbml_import.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5276301&bid=17278822)

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- python/tests/test_preequilibration.py  7
- python/tests/conftest.py  4
- python/tests/test_parameter_mapping.py  6
- python/tests/test_pandas.py  10
- python/tests/test_hdf5.py  7
- python/tests/test_pysb.py  12
- python/tests/test_sbml_import.py  9
- python/tests/test_misc.py  4
- python/tests/test_petab_import.py  6
- python/tests/test_ode_export.py  11
- python/tests/test_swig_interface.py  9
         

Clones added
============
- python/tests/test_sbml_import.py  5
- python/tests/test_misc.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5276301&bid=17278822)

**Comment by dweindl** [comment]
> Would be great if coverage remains the same :D

Overall coverage went up. What went down, should be PEtab-related things that are happening on github. That still doesn't work properly. To be addressed separately. Checking the diff on PEtab doesn't seem to work to well at the moment.

**Comment by FFroehlich** [comment]
uuuhm, what happened to `./tests/testModels.py`?

**Comment by dweindl** [comment]
> uuuhm, what happened to `./tests/testModels.py`?

Oops. My fault. File still exists, but accidentally removed it from the travis run. Will try to fix tomorrow.

**Pull request merged**
