### PR TITLE
Fix sign in undamped Newton step.

### PR DESCRIPTION
**Pull request by paszkow**
First, in NewtonSolver::getStep() a passed-in delta vector gets
a reverse sign by calling 'delta->minus();' and then its passed to
NewtonSolver::linsolveSPBCG via NewtonSolver::solveLinearSystem
where the sign is again reversed (xdot = *ns_delta; xdot.minus();)

Therefore -gamma must be applied in the Newton step otherwise the
Newton method does not converge at all.

### CODE REVIEW

**Comment by paulstapor** [comment]
I'll look into that today. However, the Newton solver worked fine with the direct solvers lately... So I'm not sure: Would your change also work for the non-iterative solvers?

**Comment by paszkow** [comment]
So probably this change will make direct solvers not work anymore. Another possible fix would be to restore a previous sign of gamma and remove the line xdot.minus() from the function NewtonSolverIterative::linsolveSPBCG.

**Comment by paulstapor** [comment]
Okay, thanks! I'll check that out this afternoon and see, whether I get that done.

**Comment by FFroehlich** [comment]
Sounds like we need to implement a small unit test.

**Comment by paulstapor** [comment]
Okay, I just checked it:
just flipping the sign spoils convergence for direct solvers. So we need to go for something more specific here. I'll dig a bit deeper into that...

**Comment by paulstapor** [comment]
Okay, for some reason, the hand-crafted, iterative linear solver returns an update vector which is just flipped when compared to the direct solvers...
It's not exactly a beautiful solution, but the easiest possible fix for that which does not spoil anything, would be 
inserting on line after line 372 of newton_solver.cpp  with
`rhs->minus();`
At lest locally on my computer, that does the job..

**Comment by dweindl** [comment]
@FFroehlich @paulstapor Is this to be merged?

**Comment by FFroehlich** [comment]
I'd say yes.

**Pull request merged**
