### PR TITLE
Fix CI: doxygen / ghostscript

### PR DESCRIPTION
**Pull request by dweindl**
CI currently fails due to doxygen / ghostscript interaction. Therefore build latest doxygen from github.

~Blocked by https://github.com/doxygen/doxygen/issues/7411~

Using https://github.com/doxygen/doxygen/pull/7483/ for this moment. Needs to be changed to upstream doxygen repository once accepted.

### CODE REVIEW

**Comment by FFroehlich** [comment]
@dweindl whats the plan for this PR? Seems like the problem was resolved independently.

**Comment by dweindl** [comment]
> @dweindl whats the plan for this PR? Seems like the problem was resolved independently.

Was it? All recent travis runs i saw were still failing. Want to merge as soon as doxygen is fixed.

**Comment by FFroehlich** [comment]
> > @dweindl whats the plan for this PR? Seems like the problem was resolved independently.
> 
> Was it? All recent travis runs i saw were still failing. Want to merge as soon as doxygen is fixed.

Huh? How where you able to merge PRs if this was failing?

**Comment by dweindl** [comment]
> Huh? How where you able to merge PRs if this was failing?

Special privileges... Otherwise couldn't have merged anything during the last 2 months.

**Comment by FFroehlich** [comment]
> > Huh? How where you able to merge PRs if this was failing?
> 
> Special privileges... Otherwise couldn't have merged anything during the last 2 months.

😭

**Pull request merged**
