### PR TITLE
[WIP] Remove deprecated function amici.assignmentRules2observables and use …

### PR DESCRIPTION
**Pull request by dweindl**
…petab.sbml.assignment_rules_to_dict

NOTE: depending on the decision regarding https://github.com/ICB-DCM/PEtab/issues/201 which might remove the PEtab function used here, we might want to drop that PR. Waiting.

### CODE REVIEW

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/ICB-DCM/AMICI/pullRequest?prid=4685565&bid=15668822)

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/ICB-DCM/AMICI/pullRequest?prid=4685565&bid=15668822)

**Comment by FFroehlich** [comment]
updates on this?

**Comment by dweindl** [comment]
> updates on this?

This PR became obsolete, as the respective functions will be removed in PEtab. Dunno how we want to handle things in AMICI. See also #927.

**Pull request closed without merging**
