### PR TITLE
Fix(core) Fix (re)initialization of sensitivities if ExpData::fixedParametersPreequilibration is set

### PR DESCRIPTION
**Pull request by dweindl**
Previously the solver was initialized when `Model` had the orginal `fixedParameters` set instead of those from `ExpData::fixedParametersPreequilibration` leading to potentially wrong initial sensitivities being used and resulting in incorrect `sllh`.

### CODE REVIEW

**Comment by dweindl** [comment]
@FFroehlich : This fixes my issues of wrong sllh for initial state parameters for preequilibration. Not sure though if this is the smartest way to go.

**Comment by FFroehlich** [comment]
Looks like its breaking the preequilibration testcase, will have to have a close look over the weekend.

**Comment by dweindl** [comment]
> Looks like its breaking the preequilibration testcase, will have to have a close look over the weekend.

Great, thanks. For other test case, see `cd tests/petab_test_suite; python -m  pytest -s --petab-cases=10` ([data](https://github.com/PEtab-dev/petab_test_suite/tree/master/cases/0010)) on https://github.com/ICB-DCM/AMICI/tree/feature_petab_initial_states.

**Comment by FFroehlich** [comment]
For me petab tests on this branch fail with 
```
        ##########################################################################
        # initial states
        # Initial states have been set during model import based on the SBML model.
        # If initial states were overwritten in the PEtab condition table, they are
        # applied here. We never change amici_model.x0 here (and assume it contains
        # the original values; we only change ExpData.x0.
    
        species = [col for col in petab_problem.condition_df
                   if petab_problem.sbml_model.getSpecies(col) is not None]
        if species:
            x0 = amici_model.getInitialStates()
            species_ids = amici_model.getStateIds()
            for species_id in species:
                if not np.issubdtype(petab_problem.condition_df[species_id].dtype,
                                     np.number):
                    raise NotImplementedError(
                        "Support for parametric overrides for initial states "
                        "is not yet implemented.")
    
>               species_idx = species_ids.find(species_id)
E               AttributeError: 'tuple' object has no attribute 'find'
```

**Comment by dweindl** [comment]
This does not look like the AMICI version from that branch (https://github.com/ICB-DCM/AMICI/blob/feature_petab_initial_states/python/amici/petab_objective.py#L370). Wrong environment?

**Comment by FFroehlich** [comment]
> This does not look like the AMICI version from that branch (https://github.com/ICB-DCM/AMICI/blob/feature_petab_initial_states/python/amici/petab_objective.py#L370). Wrong environment?

But this is https://github.com/ICB-DCM/AMICI/blob/07ca258c4b6ea2f66f11965a0a82f0f627c0dae4/python/amici/petab_objective.py#L448

**Comment by FFroehlich** [comment]
ah sorry didnt read the above message carefully enough

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/forwardproblem.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5138215&bid=16881696)

**Comment by FFroehlich** [comment]
issue was that information from `model->initialize` was not getting propagated to the solver. Calling `updateAndReinitStatesAndSensitivities` fixed that but caused other problems. Moving `solver->setup` into handlePreequilibration fixes the problem although its arguably a bit intransparent now where solver setup happens.

**Comment by FFroehlich** [comment]
but all tests should pass with the proposed changes

**Comment by dweindl** [comment]
Great! Thanks for looking into that!

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/forwardproblem.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5138215&bid=16881696)

**Comment by dweindl** [comment]
Can be merged?

**Comment by FFroehlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/forwardproblem.cpp  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ICB-DCM/AMICI/pullRequest?prid=5138215&bid=16881696)

**Comment by FFroehlich** [comment]
Yes

**Pull request merged**
