### PR TITLE
Add support for abs() in Python SBML import

### PR DESCRIPTION
**Pull request by paulstapor**
So far, for some models an occuring absolute value in the sbml was mapped to the function `abs`. However, sympy only knows `Abs`... This lead to an error in the import. Should be fixed now... (waiting for checks anyhow...)

### CODE REVIEW

**Comment by FFroehlich** [comment]
is this ready to merge?

**Comment by paulstapor** [comment]
I actually wanted to implement some functionality beyond this in this branch, like assuming positivity in the arguments of logarithms (in biomodels, there are some (few) cases, in which this is needed). However, at this point, it works t least for absolute values and it doesn't harm, so it can go into the develop branch, I think...

**Comment by paulstapor** [comment]
But I did not yet run the sbml test-suite, good point!
Will do that, but this change here is not super urgent...

**Comment by dweindl** [comment]
*ping*

**Comment by FFroehlich** [comment]
### **_ping_**

**Comment by yannikschaelte** [comment]
**PONG** ;)

**Comment by FFroehlich** [comment]
failing in this: 201, 279, 998, 1288, 1551. Not all of these seem to be related to the changes introduced here so it looks like somebody messed up before.

**Comment by paulstapor** [comment]
okay, thanks for this. As this PR seems to make trouble (and as I am on holiday and moving my flat this week and hence have limited time for this right now) I suggest to take it down and fix what's wrong first?

**Comment by dweindl** [comment]
> Did you run the sbml testsuite after modifying this?

I just did. Fixes `abs()`issues in 4 test cases which now fail for different reasons:

```
1520c1542
< TestCase 01516 was skipped: Encountered unsupported expression "ceil" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a Stoichiometry: "ceil(0.5)"!
---
> TestCase 01516 was skipped: Encountered unsupported expression "abs" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a Stoichiometry: "abs(-1)"!
1565c1587
< TestCase 01561 was skipped: Encountered unsupported expression "ceil" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a Stoichiometry: "ceil(0.5)"!
---
> TestCase 01561 was skipped: Encountered unsupported expression "abs" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a Stoichiometry: "abs(-1)"!
1568c1590
< TestCase 01564 was skipped: Encountered unsupported expression "ceil" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a KineticLaw: "ceil(0.5)"!
---
> TestCase 01564 was skipped: Encountered unsupported expression "abs" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a KineticLaw: "abs(-1)"!
1570c1592
< TestCase 01566 was skipped: Encountered unsupported expression "ceil" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a Rule: "ceil(S1_stoich/4)"!
---
> TestCase 01566 was skipped: Encountered unsupported expression "abs" of type "<class 'sympy.core.function.UndefinedFunction'>" as part of a Rule: "abs(-S1_stoich)"!
```

**Pull request merged**
